credentials:
  usernames:
    auditor:
      email: auditor@empresa.com
      name: Auditor Líder
      password: "$2b$12$Y3PAy3bAZ3K4ywrLmiaVNuQzor6sXF4yHX3i8JthT9oTLru.P1Yee"
    admin:
      email: admin@empresa.com
      name: Administrador
      password: "$2b$12$Y3PAy3bAZ3K4ywrLmiaVNuQzor6sXF4yHX3i8JthT9oTLru.P1Yee"

cookie:
  expiry_days: 1
  key: "Xk9mP2vL7nQ4wR8jT1yB6fH3dS5gA0eZcNuYiOxWq"
  name: "auditor_iso_session"

pre-authorized:
  emails:
    - auditor@empresa.com
    - admin@empresa.com
